Fix implicit-fallthrough warning/error in GCC 7
GCC 7 now warns about implicit fallthrough, causing the build to fail
(due to -Werror) when compiling lib/fmt/xml/snk/element.c.

element.c: In function ‘xml_snk_element_addpv’:
element.c:229:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
                 (void)va_arg(*pap, const char *);
                 ^
element.c:230:13: note: here
             case XML_SNK_ELEMENT_NT_COMMENT:
             ^~~~